"""Original teaching notes accompanying distinct, attributed Lichess positions."""
RAW=r'''
mateIn1|Mate in one|Checkmate is a complete restriction of the enemy king. Find a legal check, then prove there is no king escape, capture of the checker, or interposition.|Inspect the king's flight squares before choosing a check. A protected queen or a distant rook may cover the last escape in different ways.|A checking piece next to the king must be protected unless the king cannot capture it for another legal reason.
mateIn2|Mate in two|A mating combination must survive the defender's reply. The first move should force a position in which a second move ends the game against every defense.|Identify the likely mating square and the defender that prevents it. Calculate the forcing move that removes that resource.|The displayed line is one recorded defense. Test other legal replies instead of assuming the defender must copy it.
mateIn3|Mate in three|Longer mating lines require accurate visualization. Track the king's square, opened lines, and every sacrificed piece through the entire sequence.|Work backward from a mating pattern, then calculate forward with the opponent choosing the strongest defense.|Do not stop at a promising check. The final mating position must still be legal after every intervening move.
backRankMate|Back-rank mates|A king trapped behind its own pawns may have no flight square when a rook or queen reaches its back rank. The entry square and its defenders are critical.|Inspect the king's pawn shelter, then find how a heavy piece can enter the last rank or remove its defender.|A flight square, an interposition, or a countercheck may refute an apparent mate. Check all three before sacrificing material.
smotheredMate|Smothered mates|A knight can check a king surrounded by its own pieces. Those pieces become a cage because a knight check cannot be blocked.|Trace the knight's route to the checking square and identify the enemy pieces that deny the king its escape squares.|A familiar pattern is insufficient if the knight can be captured. Verify protection and every legal king move.
anastasiaMate|Anastasia mating nets|An Anastasia-type net uses a knight to restrict king escapes while a rook or queen checks along an edge file. Removing a pawn shield can be the crucial preparation.|Locate the knight's controlled flight squares and the heavy piece's checking line. Follow how the combination opens that line.|The knight is often a supporting piece rather than the final checker. Do not overlook its quiet control of escape squares.
arabianMate|Arabian mating nets|In an Arabian-type net a rook and knight cooperate near a corner. One piece gives check while the other protects the rook or controls escape squares.|Look for a cornered king, a rook entry, and a knight square that links protection with restriction.|A mating label describes a recurring arrangement, not a substitute for checking the exact legal defenses on this board.
hookMate|Hook mating nets|A hook-type mating net combines rook pressure with knight control and supporting pawn geometry. The supporting pieces can matter more than the apparent value of a sacrifice.|Identify the final checking line and then trace which friendly pieces protect the attacker and control the king's exits.|Recount the king's legal replies after each move. A changed pawn placement can destroy an otherwise familiar mating pattern.
fork|Forks and double attacks|A fork attacks multiple targets at once. The combination works when the defender cannot save everything or generate a stronger forcing reply.|Look for checking forks first, then double attacks on queens, rooks, and undefended pieces. Follow the line until the material is actually collected.|Two attacked pieces do not guarantee a gain if the forking piece can be captured or one target moves with check.
pin|Pins and pressure|A pin limits a piece because moving it exposes a more important target. A pin to the king restricts legality; a pin to another piece changes the practical cost of moving.|Trace the line through attacker, pinned piece, and rear target. Test whether the pinned piece is being counted as a defender it cannot really be.|A pinned piece can sometimes move along the line, capture the pinning piece, or answer with a forcing resource.
skewer|Skewers|A skewer puts the more important target in front. When that target moves, a piece behind it may be lost. Checks make the geometry especially forcing.|Search ranks, files, and diagonals where two enemy pieces line up. Calculate the first target's legal responses.|The defender may block, capture the attacker, or protect the rear piece while moving the front one. Alignment alone is not enough.
discoveredAttack|Discovered attacks|Moving a blocker can uncover a rook, bishop, or queen attack. The moving piece may create a second threat, giving the defender too many problems at once.|Find a friendly piece between a slider and an enemy target, then inspect its forcing moves and captures.|Choose the blocker's destination carefully. An uncovered attack may fail if the opponent has a stronger check or can capture the slider.
discoveredCheck|Discovered checks|A discovered check opens a line toward the king by moving the blocking piece. Because check must be answered, the moving piece may gain a free tempo for another threat.|Trace the hidden checking line first. Then examine where the blocker can move to attack or capture something important.|The checking line must actually be clear, and moving the blocker must not expose your own king to check.
doubleCheck|Double checks|Double check attacks the king with two pieces at once. The defender must move the king, so an ordinary block or capture of just one checker cannot solve the problem.|Locate the slider that can be uncovered and a checking destination for its blocker. Then calculate the king's legal escapes.|Double check is forcing, but not necessarily winning. The king may escape to safety if the follow-up is missing.
attraction|Attraction tactics|Attraction draws a piece onto a square where a later tactic becomes possible. Sacrifices often work by changing the king's or queen's location rather than winning immediately.|Ask which enemy piece must be moved to a specific square for your next check, fork, or mating pattern to work.|The opponent may decline the offered material. Compare refusal with the recorded continuation before calling the sacrifice forced.
deflection|Deflection tactics|Deflection distracts a defender from a critical job. Its new square matters less than the fact that it no longer guards the original target.|Name the defender's job, find a forcing way to divert it, and calculate the move that exploits the abandoned square.|A replacement defender or an intermediate check can keep the target safe even after the original defender moves.
clearance|Clearance tactics|A clearance move vacates a square or opens a line for another piece. The clearing piece may sacrifice itself to gain the time needed for the follow-up.|Identify the rook, bishop, queen, or knight that needs access, then locate the friendly piece blocking its route or destination.|Opening a line helps only if your next move is timely. The defender may close the line or create a stronger threat.
interference|Interference tactics|Interference interrupts a defensive line between enemy pieces. Occupying one square can make a previously protected target vulnerable or prevent an important recapture.|Trace the defender's line to its target and inspect forcing moves onto the intervening squares.|Capturing the interposing piece may restore defense. Calculate which captures are legal and whether they permit another tactic.
intermezzo|Intermediate moves|An intermediate move interrupts an expected sequence with a stronger immediate threat. Instead of recapturing automatically, use a check or another forcing move to change the result.|Before every routine recapture, scan checks, queen attacks, and mating threats. Return to the original capture only if it still helps.|The postponed recapture may disappear. The intermediate move must win enough or preserve the right to recover material.
hangingPiece|Loose-piece tactics|An undefended or tactically undefendable piece can turn an ordinary position into a combination. The first task is to distinguish a truly free capture from a poisoned one.|List the loose enemy pieces and check whether a forcing move can expose or attack more than one of them.|A piece may appear hanging because its defender is indirect: taking it might allow mate, a fork, or a stronger capture.
trappedPiece|Trapping a piece|A trapped piece lacks safe retreat squares. Winning it usually requires restricting its routes before attacking it, or forcing it into a cage.|Trace every plausible escape square for the target, including captures and counterchecks. Then find the move that closes the remaining route.|An attacked piece is not trapped if it can give check, trade itself favorably, or open an escape through a sacrifice.
exposedKing|Exposed-king tactics|An exposed king gives the attacker checks and access to nearby squares. Coordinate pieces so the checks drive it into a worse net rather than toward safety.|Inspect open files, diagonals, and unprotected squares around the king. Calculate checks in an order that preserves the attack.|A king without pawns is not automatically mated. Count active attackers and examine escapes toward friendly pieces.
kingsideAttack|Kingside attacks|A kingside attack succeeds when pieces and pawn breaks create concrete threats near the king. The attack must arrive before the defender can exchange attackers or counter in the center.|Count the pieces that can join immediately, identify an entry square, and calculate the defender's checks and exchanges.|Do not count distant pieces as attackers unless they can reach useful squares in time. Every preparatory move gives the defender a turn.
queensideAttack|Queenside attacks|An attack on the queenside can target a castled king, a vulnerable pawn, or trapped pieces. Files and entry squares matter more than simply advancing flank pawns.|Locate the critical target and which pawn or piece move opens a route toward it. Check whether central counterplay interrupts the plan.|The board's left half is not inherently safe. Queen checks and rook entries can make a queenside king as vulnerable as a kingside one.
sacrifice|Calculated sacrifices|A sacrifice exchanges material for a concrete benefit. The benefit may be mate, a stronger attack, a recovered investment, or lasting activity; it must be shown through moves.|State what the sacrifice changes: a defender, a line, a king square, or a critical tempo. Calculate acceptance and plausible refusal.|An attractive attacking picture is not compensation by itself. Continue until the resulting position can be evaluated honestly.
quietMove|Quiet tactical moves|A quiet move can win by threatening something the defender cannot meet, even though it gives no check and makes no capture. It often supplies the missing support in a near-working combination.|Use failed forcing lines to identify an escape square or defender. Search for a move that removes that resource while keeping the threat.|Because the move is not forcing by check, the opponent has time for counterplay. Test every serious check and direct threat.
defensiveMove|Active defensive resources|The best defense may create a threat, exchange an attacker, or change the geometry of the attack. Identify the opponent's concrete idea before selecting a response.|Name the threatened move and the conditions it requires. Look for a move that breaks one of those conditions with tempo.|A defensive puzzle may aim to preserve equality rather than win. Judge success against the threat, not only the final material count.
capturingDefender|Capture the defender|Removing a key defender can transform a protected square into a winning entry. The defender's function explains why the first capture matters.|Identify the protected target, capture its essential defender, and calculate the follow-up after each plausible recapture.|Do not assume a defender is unique. Another piece may take over its job, or the opponent may decline to recapture.
promotion|Promotion combinations|An advanced pawn can turn a tactical sequence into a new queen or another useful piece. Promotion may occur with capture or check, and the choice of piece can change the outcome.|Calculate the pawn's route, the safety of the promotion square, and whether the new piece can survive or give a decisive check.|Always inspect stalemate and underpromotion resources. A queen is usually strongest, but the exact position determines the choice.
advancedPawn|Advanced-pawn tactics|A pawn near promotion forces the defender to respect urgent threats. Its strength can create forks, deflections, or mating ideas even when it never actually promotes.|Count the remaining pushes and identify the blocker. Look for forcing moves that remove or distract that blocker.|A far-advanced pawn may be weak if unsupported. Check whether the opponent can capture it with tempo or blockade it permanently.
rookEndgame|Rook-ending tactics|Rook endings combine pawn races with checks, cutoffs, and promotion tactics. Activity is vital, but the exact move order often decides whether a pawn can advance safely.|Check the kings' exposure, the rooks' checking distance, and the passed pawns. Calculate forcing checks before applying a general rook-ending rule.|A routine rook placement can miss a skewer or promotion with check. Let concrete tactics override a guideline when they conflict.
pawnEndgame|Pawn-ending calculation|With only kings and pawns, a single tempo can reverse the result. Calculate opposition, capture routes, promotion races, and reserve pawn moves precisely.|Count actual king moves and pawn pushes, then include whose turn it is and whether promotion gives check.|Do not enter a pawn ending because it looks simple. Rook-pawn exceptions and zugzwang can make a material advantage irrelevant.
bishopEndgame|Bishop-ending decisions|A bishop ending depends on diagonal access, pawn color, king activity, and promotion squares. Tactics can arise when a bishop must perform two defensive jobs.|Trace the bishop's line to each target and identify pawns that can break its coverage or force it to move.|Same-colored and opposite-colored bishop endings have different tendencies, but neither label replaces calculation of the actual pawn races.
knightEndgame|Knight-ending routes|Knight endings reward exact route calculation. Forks can change a pawn race, while a distant passer may outrun the knight's short-range movement.|Map the knight's checking moves and its route to the critical blockade square. Count moves rather than judging distance by appearance.|A knight changes color with every move and may need a detour. Check the route square by square before trusting a race estimate.
queenEndgame|Queen-ending tactics|Queens combine long-range checks with promotion support. King shelter and the order of checks often matter more than a small material lead.|Inspect perpetual-check possibilities, queen trades, and checks that gain a tempo for a passed pawn.|A favorable-looking queen exchange can lead to a drawn pawn ending. Evaluate the new ending before simplifying.
queenRookEndgame|Queen-and-rook endings|When queens and rooks remain, mating threats coexist with endgame pawn races. Coordination and king shelter remain essential even on a sparse board.|Look for heavy-piece batteries, skewers, and checks that force a defender away from a promotion square or pawn.|Do not activate the king as casually as in a pure pawn ending. The remaining heavy pieces can still generate a mating net.
'''
THEMES={}
for row in RAW.strip().splitlines():
    key,title,principle,method,caution=row.split('|')
    THEMES[key]=dict(title=title,principle=principle,method=method,caution=caution)
assert len(THEMES)==36
